version: "2"
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    networks:
      - default

  wordpress:
    # image: wordpress:latest
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile-wp
    container_name: wp
    volumes:
      - "./wordpress:/var/www/html"
    working_dir: "/var/www/html"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - default

networks:
  default:
    driver: bridge